apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-deployment

  template:
    metadata:
      labels:
        name: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest

        - name: multitool
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "8443"



