apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    name: nginx-deployment
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 80
      name: nginx-http

    - protocol: TCP
      port: 9002
      targetPort: 8080
      name: mtool-http

