apiVersion: v1
kind: Service
metadata:
  name: nginx-node-svc
spec:
  selector:
    name: init-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx-http
      nodePort: 30001
  type: NodePort