stages:
  - build


build-image:
  stage: build
  only:
    - main
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD sinersis.gitlab.yandexcloud.net:5050
    - docker build -t sinersis.gitlab.yandexcloud.net:5050/sinersis89/learn:hello-gitlab-$CI_COMMIT_SHORT_SHA --platform linux/amd64 .
    - docker push sinersis.gitlab.yandexcloud.net:5050/sinersis89/learn:hello-gitlab-$CI_COMMIT_SHORT_SHA