apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    name: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1180
      name: mtool-http

    - protocol: TCP
      port: 8080
      targetPort: 80
      name: nginx-http