---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: ClickHouse
      block:
        - name: CLICKHOUSE | Distribute
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
            mode: "0644"
          with_items: "{{ clickhouse_packages }}"

        - name: CLICKHOUSE | Install
          become: true
          ignore_errors: "{{ ansible_check_mode }}"
          ansible.builtin.yum:
            name:
              - ./clickhouse-common-static-{{ clickhouse_version }}.rpm
              - ./clickhouse-client-{{ clickhouse_version }}.rpm
              - ./clickhouse-server-{{ clickhouse_version }}.rpm
            state: present
          notify: Start clickhouse service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: CLICKHOUSE | Create database
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.command: "bash -c \"clickhouse-client -q 'create database logs;'\""
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  tasks:
    - name: Vector
      block:
        - name: VECTOR | Distribute
          ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/0.34.1/vector-{{ vector_version }}.x86_64.rpm"
            dest: "./vector-{{ vector_version }}.rpm"
            mode: "0644"

        - name: VECTOR | Install
          become: true
          ignore_errors: "{{ ansible_check_mode }}"
          ansible.builtin.yum:
            name:
              - ./vector-{{ vector_version }}.rpm
            state: present

        - name: VECTOR | Config
          ansible.builtin.template:
            src: ./templates/vector.j2
            dest: ./vector.yaml
            mode: "0644"

- name: Install LightHouse
  hosts: lighthouse
  handlers:
    - name: Start-nginx
      become: true
      changed_when: false
      ansible.builtin.command: "nginx"

    - name: Reload-nginx
      become: true
      changed_when: false
      ansible.builtin.command: "nginx -s reload"

  tasks:
    - name: EPEL | Install
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.yum:
        name:
          - epel-release
        state: present

    - name: GIT | Install Git
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.yum:
        name:
          - git
        state: present

    - name: NGINX | Install
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.yum:
        name:
          - nginx
        state: present
      notify: Start-nginx

    - name: NGINX | Config
      become: true
      ansible.builtin.template:
        src: ./templates/nginx.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Reload-nginx

    - name: LIGHTHOUSE | Install
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.git:
        repo: https://github.com/VKCOM/lighthouse.git
        dest: ./lighthouse
        version: master
        accept_hostkey: true


    - name: LIGHTHOUSE | Nginx Config
      become: true
      ansible.builtin.template:
        src: ./templates/lighthouse.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "0644"
      notify: Start-nginx
