{
 "title": "Learn",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\",fstype=\"ext4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU LA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(avg(node_load15{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) * 100) / count(count by(cpu) (node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}))",
     "legendFormat": "1 min"
    },
    {
     "expr": "(avg(node_load5{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) * 100) / count(count by(cpu) (node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}))",
     "legendFormat": "5 min"
    },
    {
     "expr": "(avg(node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) * 100) / count(count by(cpu) (node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}))",
     "legendFormat": "15 min"
    }
   ]
  }
 ]
}