apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-deployment

  template:
    metadata:
      labels:
        name: nginx-deployment
    spec:
      volumes:
        - name: nginx-page
          configMap:
            name: nginx-config
            items:
              - key: html_page
                path: index.html
        - name: nginx-conf
          configMap:
            name: nginx-config
            items:
              - key: default_conf
                path: default.conf
        - name: nginx-crt
          secret:
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - mountPath: /var/www/html/
              name: nginx-page
            - mountPath: /etc/nginx/conf.d/
              name: nginx-conf
            - mountPath: /etc/custom-cert/
              name: nginx-crt

        - name: multitool
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: multitool-config
                  key: http_port
            - name: HTTPS_PORT
              valueFrom:
                configMapKeyRef:
                  name: multitool-config
                  key: https_port


