apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  html_page: |
    <!doctype html>
    <html lang="en">
    <head>
        <title>Hello Netology</title>
    </head>
    <body>
        File generate in config map
    </body>
    </html>
  default_conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /var/www/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
    

  default_https_conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /var/www/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
    server {
            listen       443 ssl;
            listen  [::]:443 ssl;
            server_name  localhost;
    
            ssl_certificate    /etc/cssl/tls.crt;
            ssl_certificate_key /etc/cssl/tls.key;

            location / {
                root   /var/www/html;
                index  index.html index.htm;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }